import turtle
t = turtle.Pen()
t.right(90)
t.pencolor("red")
t.penup()
t.speed(6)
t.forward(90)
t.pendown()
t.pensize(4)
t.right(140)
t.begin_fill()
t.forward(235)
t.color("blue","yellow")
t.right(180)
t.circle(90,extent=-200)
t.left(120)
t.circle(90,extent=-200)
t.left(180)
t.forward(235)
t.end_fill()
turtle.done()

